### ISSUE TITLE
Passing the bounding box info

### ISSUE THREAD

**Issue by aakif1996-blip** [visionml/pytracking#142]
Excellent tracker first of all, I have a custom video that I want to use for testing the tracker (using run_video.py). It works great without the bounding box and debug parameter. But while passing them, I have 2 difficulties:

- There is a coding error for the **--optional_box** parameter (Line 275 in pytracking/evaluation/ tracker.py) - it should be assert **isinstance(optional_box, (list, tuple))** but even then I am unable to pass the bounding box parameters
- I have modified the **result_path** in local.py, yet the predicted bounding box results aren't saved in the specified directory (while setting debug to 0).

The function call:
**python run_video.py dimp dimp50 video.avi --optional_box [x,y,w,h] --debug 0**

While I am new to working on python so it is likely that I may have made a simple mistake, My apologies in that case.

**Comment by goutamgmb** [comment]
Hi @aakif1996-blip 

Thanks for notifying the issues. There were some bugs in the code which should be fixed now. You can save the bounding box results now with the following function call:

python run_video.py dimp dimp50 video.avi --optional_box  x y w h --save_results

The results will be stored in the file results_directory/tracker_name/parameter_name/video_{name_of_the_video}.txt

Let me know if this works.

**Comment by aakif1996-blip** [comment]
Hi, 
I can confirm that the bugs have been rectified. Thank you for taking the time to help out.

**Comment by aakif1996-blip** [comment]
Hi, I am sorry but I just realized that I hadn't verified the working of the save_results parameter and it seems to me that it still doesn't work. I tried changing the directory in local.py yet again but it didn't save anything. Could you please provide a quick clarification yet again. Thanks in advance!

**Comment by goutamgmb** [comment]
There was another bug :( It is fixed now. Can you check with the latest commit?

**Comment by aakif1996-blip** [comment]
Yes! It is fixed now! Thank you once again for the prompt response :) But on a side note if I would like to ask you some closing comments about your tracker and its use in my application. 

I am trying to track one of the fingertip(which look completely white) using your work. The finger is resting on a green surface which is partially covered by the finger. But as soon as the finger starts moving away from the green surface, the tracker loses the target completely and gets stuck on the green surface rather than following the (white) fingertip. Could you suggest me a way to make it possible for it too just track the finger and not the green color surface ?

![dkh2_b2_t12_050](https://user-images.githubusercontent.com/59018672/80699029-03412900-8ae4-11ea-84cc-9789ee6f544d.png)

**Comment by goutamgmb** [comment]
@aakif1996-blip Firstly, the image seems overexposed. I wonder if it is possible to adjust the camera setting, or the lighting so that the fingertip doesn't just look white. Secondly, if the hand motion is too fast, you can try increasing the search area (search_area_scale parameter setting), and preferable also the image_sample_size proportionally. Third, instead of tracking only the fingertip, you can try tracking the whole finger which should be easier to track. I guess it should be easy to obtain the location of the fingertip using the bounding box for the finger.  Hope this helps!
