### ISSUE TITLE
run_tracker error

### ISSUE THREAD

**Issue by MMarvasti** [visionml/pytracking#96]
Hi, 
I've followed the installation guide to run the ECO tracker using pytracking. When I run 
python run_tracker.py eco default  --sequence 'Bolt' --debug 1
the following error is occured:
Traceback (most recent call last):
  File "../pytracking/evaluation/otbdataset.py", line 60, in _construct_sequence
    ground_truth_rect = np.loadtxt(str(anno_path), dtype=np.float64)
  File "/home/administrator/anaconda3/envs/pytracking-master/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1146, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/administrator/anaconda3/envs/pytracking-master/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1074, in read_data
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/administrator/anaconda3/envs/pytracking-master/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1074, in <listcomp>
    items = [conv(val) for (conv, val) in zip(converters, vals)]
  File "/home/administrator/anaconda3/envs/pytracking-master/lib/python3.7/site-packages/numpy/lib/npyio.py", line 781, in floatconv
    return float(x)
ValueError: could not convert string to float: '250,168,106,105'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run_tracker.py", line 90, in <module>
    main()
  File "run_tracker.py", line 86, in main
    {'use_visdom': args.use_visdom, 'server': args.visdom_server, 'port': args.visdom_port})
  File "run_tracker.py", line 38, in run_tracker
    dataset = OTBDataset()
  File "../pytracking/evaluation/otbdataset.py", line 7, in OTBDataset
    return OTBDatasetClass().get_sequence_list()
  File "../pytracking/evaluation/otbdataset.py", line 27, in get_sequence_list
    return SequenceList([self._construct_sequence(s) for s in self.sequence_info_list])
  File "../pytracking/evaluation/otbdataset.py", line 27, in <listcomp>
    return SequenceList([self._construct_sequence(s) for s in self.sequence_info_list])
  File "../pytracking/evaluation/otbdataset.py", line 62, in _construct_sequence
    ground_truth_rect = np.loadtxt(str(anno_path), delimiter=',', dtype=np.float64)
  File "/home/administrator/anaconda3/envs/pytracking-master/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1146, in loadtxt
    for x in read_data(_loadtxt_chunksize):
  File "/home/administrator/anaconda3/envs/pytracking-master/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1071, in read_data
    % line_num)
ValueError: Wrong number of columns at line 496

Please let me know what the problem is.
Thank you in advance.

**Comment by MMarvasti** [comment]
Dear all,

Could you please provide more specific guides to install, initialize (paths to datasets and etc.) and run these trackers?

BR,

**Comment by martin-danelljan** [comment]
Seems your annotation file is corrupted. Where did you get the OTB dataset?

Please check the detailed [installation instructions](https://github.com/visionml/pytracking/blob/master/INSTALL.md) and [instructions to run the trackers](https://github.com/visionml/pytracking/tree/master/pytracking).

**Comment by MMarvasti** [comment]
I was set the wrong path to the OTB dataset; the error was solved. 
Thank you Martin for your reply.

**Comment by Jack-zhangluyao** [comment]
Hi, I come aross the same question, I have checked the path of OTB dataset in pytracking/pytracking/local.py for many times,but this problem still exist. could you show me your setting path of this dataset,I can use this as a reference.thanks in adance,hope your reply @MMarvasti
